# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: Install prerequisites
  become: yes
  package:
    name: unzip
    state: present

- name: Check ovftool zip file stats
  stat:
    path: "{{ tmp_dir }}/{{ ovf_zip }}"
    get_checksum: yes
    checksum_algorithm: md5
  register: ovfzip_stat

- name: Download ovftool zip file
  get_url:
    url: "{{ ovf_zip_url }}"
    dest: "{{ tmp_dir }}"
  when: (not ovfzip_stat.stat.exists or (ovfzip_stat.stat.checksum != ovf_zip_md5))
  register: dload

- name: Check binary stats
  stat: path="{{ ovf_dir }}/ovftool/ovftool"
  register: ovf_stat

- name: Make bundle executable
  file:
    mode: 0755
    path: "{{ tmp_dir }}/{{ ovf_zip }}"

- name: Install OVFtool
  become: yes
  shell: "{{ tmp_dir }}/{{ ovf_zip }} --eulas-agreed --required --console"
  when: dload.changed or (not ovf_stat.stat.exists)
  tags:
    - skip_ansible_lint

- name: Test that it operates
  command: "ovftool --help"
  changed_when: False
